modLoader="javafml"
loaderVersion="[47,)"
license="Apache-2.0 license"
issueTrackerURL="https://github.com/PhantomLoader/PhantomLoader/issues"

[[mods]]
modId="phantom"
version="${file.jarVersion}"
displayName="Phantom Library"
#updateJSONURL="https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/"
displayURL="https://github.com/PhantomLoader/PhantomLoader"
logoFile="logo.png"
#credits="Additional credits go here"
authors="HexagonNico"
description="A library to automate part of the process of creating mods for multiple loaders"

[[dependencies.phantom]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.phantom]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
